commands: 
  - # Create virtual environtment
    - "python"
    - "-m"
    - "venv"
    - "env"

  - # Install django
    - "./env/bin/pip"
    - "install"
    - "django"

  - # Create django project
    - "./env/bin/django-admin"
    - "startproject"

help: "Create django app"

subCommands:
  rest:
    name: "rest-framework"
    command: 
      - "../env/bin/pip"
      - "install"
      - "djangorestframework"

    parallel: true
    help: "Install and setup DjangoRestFramework"

    files: 
      rest-framework-settings:
        filepath: "<APPNAME>/settings.py"
        change: 
          split-on: "'django.contrib.staticfiles',"
          append: "\n\t'rest_framework'," 

  cors:
    name: "cors-headers"
    command: 
      - "../env/bin/pip"
      - "install"
      - "django-cors-headers"

    parallel: true
    help: "Install django-cors-headers"

    files:
      cors-installed-apps:
        filepath: "<APPNAME>/settings.py"
        change: 
          split-on: "'django.contrib.staticfiles',"
          append: "\n\t'corsheaders',"

      cors-middleware:
        filepath: "<APPNAME>/settings.py"
        change: 
          split-on: "MIDDLEWARE = ["
          append: "\n\t'corsheaders.middleware.CorsMiddleware'," 

      cors-settings:
        filepath: "<APPNAME>/settings.py"
        change: 
          split-on: ""
          append: "\n# Change in production\nCORS_ALLOW_ALL_ORIGINS = True"

  jwt:
    name: "json-web-tokens"
    command: 
      - "../env/bin/pip"
      - "install"
      - "djangorestframework-simplejwt"

    parallel: true
    help: "Add JSON Web Tokens to use for user authentication"

    files:
      jwt-settings:
        filepath: "<APPNAME>/settings.py"
        change: 
          split-on: "# Application definition"
          append: "\nREST_FRAMEWORK = {\n\t'DEFAULT_AUTHENTICATION_CLASSES': (\n\t\t'rest_framework_simplejwt.authentication.JWTAuthentication',\n\t)\n}"
