commands = [["npx", "create-next-app"]]
help = "Create nextJS app"

[subCommands.redux]
name = "Redux"
command = ["npx", "create-next-app", "--example", "with-redux-thunk"]
override = true
help = "Use redux example of create-next-app"

[subCommands.ts]
name = "Typescript"
command = ["npx", "create-next-app", "--typescript"]
override = true
help = "Use typescript with create-next-app"

[subCommands.redux-ts]
name = "Redux-Typescript"
command = ["npx", "create-next-app", "--example", "with-redux"]
override = true
help = "Use redux-typescript example of create-next-app"

[subCommands.mui]
name = "Material-UI"
command = [
  "npm",
  "install",
  "@mui/material",
  "@emotion/react",
  "@emotion/styled",
]
override = false
help = "Install material-ui library"

[subCommands.bootstrap]
name = "Bootstrap"
command = ["npm", "install", "react-bootstrap"]
override = false
help = "Install react-bootstrap library"
