commands = [["npx", "create-react-app"]]
help = "Create react app"

[subCommands.redux]
name = "Redux"
command = ["npx", "create-react-app", "--template", "redux"]
override = true
help = "Use redux template of cra"

[subCommands.ts]
name = "Typescript"
command = ["npx", "create-react-app", "--template", "typescript"]
override = true
help = "Use typescript template of cra"

[subCommands.redux-ts]
name = "Redux-Typescript"
command = ["npx", "create-react-app", "--template", "redux-typescript"]
override = true
help = "Use redux-typescript template of cra"

[subCommands.mui]
name = "Material-UI"
command = [
  "npm",
  "install",
  "@mui/material",
  "@emotion/react",
  "@emotion/styled",
]
override = false
help = "Install material-ui library"

[subCommands.bootstrap]
name = "Bootstrap"
command = ["npm", "install", "react-bootstrap"]
override = false
help = "Install react-bootstrap library"
